#!/bin/bash
# ============================================================
# Engram Setup Wizard
# Interactive setup for Semantic Memory System
# ============================================================

set -e

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║   🧠 ENGRAM SETUP WIZARD                                 ║"
echo "║   Semantic Memory System Configuration                   ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  Found existing .env file."
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Your existing .env is safe."
        exit 0
    fi
    mv .env .env.backup
    echo "✓ Backed up to .env.backup"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 STEP 1: GEMINI API KEY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open: https://aistudio.google.com/app/apikey"
echo "2. Click 'Create API Key'"
echo "3. Copy the key (starts with AIzaSy...)"
echo ""
read -p "Enter your Gemini API key: " GEMINI_KEY

if [[ ! $GEMINI_KEY =~ ^AIzaSy ]]; then
    echo "⚠️  Warning: Key doesn't start with 'AIzaSy'. Continue anyway? (y/N): "
    read -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled."
        exit 1
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 STEP 2: PINECONE SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Sign up at: https://app.pinecone.io/"
echo "2. Create new index with:"
echo "   - Dimensions: 768"
echo "   - Metric: cosine"
echo "   - Cloud: AWS (free tier)"
echo "   - Region: us-east-1"
echo ""
read -p "Press ENTER when you've created the index..."

echo ""
read -p "Enter your Pinecone API key (starts with pcsk_): " PINECONE_KEY

if [[ ! $PINECONE_KEY =~ ^pcsk_ ]]; then
    echo "⚠️  Warning: Key doesn't start with 'pcsk_'. Continue anyway? (y/N): "
    read -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled."
        exit 1
    fi
fi

echo ""
read -p "Enter your Pinecone host URL (https://...): " PINECONE_HOST

if [[ ! $PINECONE_HOST =~ ^https:// ]]; then
    echo "⚠️  Warning: URL should start with 'https://'. Continue anyway? (y/N): "
    read -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled."
        exit 1
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 STEP 3: VAULT PATH"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Enter the absolute path to your Obsidian vault or markdown folder."
echo "Example: /home/user/Documents/MyVault"
echo ""
read -e -p "Vault path: " VAULT_PATH

# Expand tilde
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

if [ ! -d "$VAULT_PATH" ]; then
    echo "⚠️  Warning: Directory '$VAULT_PATH' does not exist!"
    echo "Do you want to create it? (y/N): "
    read -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        mkdir -p "$VAULT_PATH"
        echo "✓ Created directory: $VAULT_PATH"
    else
        echo "⚠️  Continuing with non-existent path. You'll need to create it later."
    fi
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "💾 SAVING CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cat > .env << EOF
# Engram Configuration
# Generated by setup wizard on $(date)

GEMINI_API_KEY=$GEMINI_KEY
PINECONE_API_KEY=$PINECONE_KEY
PINECONE_HOST=$PINECONE_HOST
LOCAL_REPO_PATH=$VAULT_PATH
EOF

echo "✓ Configuration saved to .env"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 TESTING CONNECTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ -f ".venv/bin/python" ]; then
    PYTHON=".venv/bin/python"
elif [ -f "venv/bin/python" ]; then
    PYTHON="venv/bin/python"
else
    PYTHON="python3"
fi

if [ -f "test_connection.py" ]; then
    echo "Running connection test..."
    $PYTHON test_connection.py
    TEST_RESULT=$?
    
    if [ $TEST_RESULT -eq 0 ]; then
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo "✅ SETUP COMPLETE!"
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        echo ""
        echo "🎯 NEXT STEPS:"
        echo ""
        echo "1. Index your vault:"
        echo "   $PYTHON tool_engram_index.py"
        echo ""
        echo "3. Test search:"
        echo "   echo '{\"query\": \"test\", \"min_score\": 0.3}' | $PYTHON tool_engram_search.py"
        echo ""
        echo "3. Setup auto-indexing (optional):"
        echo "   Read README.md section 'Automatic Daily Indexing'"
        echo ""
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    else
        echo ""
        echo "⚠️  Connection test failed. Please check your API keys and try again."
        echo ""
        echo "To re-run setup: ./setup.sh"
        echo "To test manually: $PYTHON test_connection.py"
    fi
else
    echo "⚠️  test_connection.py not found. Skipping connection test."
    echo ""
    echo "✓ Configuration saved successfully!"
    echo ""
    echo "Next steps:"
    echo "1. Test: $PYTHON test_connection.py"
    echo "2. Index: $PYTHON tool_engram_index.py"
fi
